version: '2.1'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
#      - MYSQL_RANDOM_ROOT_PASSWORD='yes'
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=demo
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
    networks:
      - reactnet

  auth-service:
    image: reactive-security/auth-service:0.1.0-SNAPSHOT
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_HOST=mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306
    networks:
      - reactnet
    links:
      - mysql
    depends_on:
      - mysql

  data-service:
    image: reactive-security/data-service:0.1.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_HOST=mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306
    networks:
      - reactnet
    links:
      - mysql
    depends_on:
      - mysql

networks:
  reactnet:
    driver: bridge

volumes:
  mysql:
    driver: local
